version: '3.8'

services:
  neo-mcp-server:
    build: .
    image: r3e/neo-n3-mcp:latest
    container_name: neo-mcp-server
    environment:
      - NEO_RPC_URL=https://mainnet1.neo.coz.io:443
      - NEO_MAINNET_RPC_URL=https://mainnet1.neo.coz.io:443
      - NEO_TESTNET_RPC_URL=https://testnet1.neo.coz.io:443
      - WALLET_PATH=/app/wallets
      - NEO_NETWORK=mainnet
      - LOG_LEVEL=info
    volumes:
      - ./wallets:/app/wallets
    restart: unless-stopped
    depends_on:
      - neo-node

  # Neo N3 node
  neo-node:
    image: cityofzion/neo-go:latest
    container_name: neo-node
    ports:
      - "10332:10332"
    volumes:
      - ./neo-data:/root/.neo-go
    command: node --mainnet
    restart: unless-stopped
