[build]
  publish = "./"
  functions = "./netlify/functions"

# Redirect rule to ensure API requests are handled correctly
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect rule for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npx serve"
  port = 8888
  publish = "./" 