name: Update Badges

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  update-badges:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: Update status badges
        run: |
          # Get the latest build status
          BUILD_STATUS="passing"
          TEST_STATUS="passing"
          
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            BUILD_STATUS="failing"
            TEST_STATUS="failing"
          fi
          
          # Update README.md badges
          sed -i "s|build-.*-brightgreen.svg|build-${BUILD_STATUS}-brightgreen.svg|g" README.md
          sed -i "s|tests-.*-brightgreen.svg|tests-${TEST_STATUS}-brightgreen.svg|g" README.md
          
          if [[ "$BUILD_STATUS" == "failing" ]]; then
            sed -i "s|build-failing-brightgreen.svg|build-failing-red.svg|g" README.md
          fi
          
          if [[ "$TEST_STATUS" == "failing" ]]; then
            sed -i "s|tests-failing-brightgreen.svg|tests-failing-red.svg|g" README.md
          fi
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "Update status badges [skip ci]"
          git push 