name: Website Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'website/**'
      - '.github/workflows/website-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'website/**'
      - '.github/workflows/website-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: website/package.json

      - name: Install dependencies
        run: npm install

      - name: Install function dependencies
        run: cd netlify/functions && npm install

      - name: Install test dependencies
        run: cd tests && npm install

      - name: Run tests
        run: npm test

  functions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: website/netlify/functions/package.json

      - name: Install function dependencies
        run: cd netlify/functions && npm install

      - name: Install test dependencies
        run: cd tests && npm install

      - name: Run function tests
        run: npm run test:functions

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: website/package.json

      - name: Install dependencies
        run: npm install

      - name: Install test dependencies
        run: cd tests && npm install

      - name: Run frontend tests
        run: npm run test:frontend 